### ISSUE TITLE
Renaming folders or file is not supported - VS Code with Azure ML & Azure Blob

### ISSUE THREAD

**Issue by saimanoj18** [microsoft/vscode-azurestorage#926]
**Expected Behavior**
To be able to rename the file from Azure Blob container in VS Code

**Actual Behavior**
"Renaming folders or file is not supported"

**Steps to Reproduce the Problem**
I have connected VSCode to Azure Machine Learning account.  I am using the Azure storage extension to load the files, that lie in the Blob storage of the corresponding Azure ML workspace. I have provided screen recording which shows the steps I did. I am able to create and delete files but not able to rename them. I tried to rename a file in it, using VSCode. Then I get a notification that "Renaming folders or file is not supported".

https://user-images.githubusercontent.com/4462455/106962342-8310b980-672e-11eb-8e99-0624d05665cf.mp4

**Specifications**

Version: Azure ML 0.6.19 and VS Code 1.52.0
Platform: Ubuntu 18.04

**Comment by wwlorey** [comment]
As of right now this is by design. The blob SDK doesn't provide a method to rename and implementing that on our end is risky from the perspective of data loss.

The next best thing we could do is implement "Clone with new name" in place of "rename".

**Comment by saimanoj18** [comment]
@wwlorey  That sounds great. It should suffice the need. I am just curious, when this can be available ? 👍

**Comment by wwlorey** [comment]
@saimanoj18 I'll make sure this is brought up in our next planning meeting.

**Comment by saimanoj18** [comment]
@wwlorey Related to this, instead of renaming, I am trying the option to convert a notebook to python script. Even then, it fails. The error notifications says "Export Failed. Please check the Jupyter outpput panel for further details."

Is this export issue the same as renaming issue ? Or am I having some errors that need to be solved ?
Can you please help me through this ?

**This is the jupyter output:**
User belongs to experiment group 'jupyterTestcf'
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
Connecting to Jupyter server at https://mv-compute23.eastus2.instances.azureml.ms
https://mv-compute23.eastus2.instances.azureml.ms: Kernel started: 16a4e262-049b-48b5-ba52-1721ce66a971
https://mv-compute23.eastus2.instances.azureml.ms: Kernel started: 71cb6a29-e9e5-4d51-bc6d-9ebfdf055306
https://mv-compute23.eastus2.instances.azureml.ms: Creating new notebook 
https://mv-compute23.eastus2.instances.azureml.ms: Kernel started: ba22e030-b16a-4f3d-ac93-92af3d5be496
Error 2021-02-05 00:22:14: Export failed [Error: Importing notebooks requires Jupyter nbconvert to be installed.
	at u.getExportInterpreter (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:32:546101)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async _.export (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:251215)
	at async c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:428598
	at async u.waitWithStatus (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:805850)
	at async E.importNotebookOnFile (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:428521)
	at async E.listenForErrors (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:423814)
	at async b._executeContributedCommand (c:\Users\sprakhya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88509)]
Error 2021-02-05 00:23:20: Export failed [Error: Importing notebooks requires Jupyter nbconvert to be installed.
	at u.getExportInterpreter (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:32:546101)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async _.export (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:251215)
	at async c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:428598
	at async u.waitWithStatus (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:805850)
	at async E.importNotebookOnFile (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:428521)
	at async E.listenForErrors (c:\Users\sprakhya\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:423814)
	at async b._executeContributedCommand (c:\Users\sprakhya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88509)]

**Comment by wwlorey** [comment]
@saimanoj18 If you're trying to get around the renaming problem, it may be easier to just create a new blob with the preferred name and copy over the contents of the old blob.

If that doesn't fix your problem, I'd recommend reaching back out to the [ML extension](https://github.com/microsoft/vscode-tools-for-ai) team. It looks like they own the scenario you're having problems with.

**Comment by saimanoj18** [comment]
@wwlorey  Hi Will, My last question was not necessarily about renaming issue. Its about using another option that shows up when we right click on a file name in VSCode Azure storage plugin. It gives an option to convert a python notebook to python script. When I try to do that, I get an error as posted in previous message. Can you please see and let me know if its an issue from VSCode or my local setup issue ?

**Comment by wwlorey** [comment]
@saimanoj18 I see - yeah the option to "convert to python script" isn't coming from the Azure Storage extension, it's likely from the Machine Learning extension. I recommend you file an issue [here](https://github.com/microsoft/vscode-tools-for-ai) for help with that.

**Comment by saimanoj18** [comment]
Sure, thank you for your support @wwlorey
