### ISSUE TITLE
remote connection failed to reconnect

### ISSUE THREAD

**Issue by RaspiRepo** [microsoft/vscode-azurestorage#949]
Connected to remote server (ssh), after inactivity from Vscode ssh connection broken. But unable to reconnect same ssh session with same window. Need to close and open in another window with remote connection. 

`[01:06:28.542] Log Level: 2
[01:06:28.546] remote-ssh@0.64.0
[01:06:28.546] darwin x64
[01:06:28.552] SSH Resolver called for "ssh-remote+192.168.0.114", attempt 1
[01:06:28.553] "remote.SSH.useLocalServer": true
[01:06:28.554] "remote.SSH.sshPath": undefined
[01:06:28.554] "remote.SSH.sshConfigurationFile": /Users/sku/.ssh/config
[01:06:28.555] "remote.SSH.useFlock": true
[01:06:28.555] "remote.SSH.lockfilesInTmp": false
[01:06:28.555] "remote.SSH.localServerDownload": auto
[01:06:28.555] "remote.SSH.remoteServerListenOnSocket": false
[01:06:28.555] "remote.SSH.showLoginTerminal": true
[01:06:28.555] "remote.SSH.defaultExtensions": []
[01:06:28.556] SSH Resolver called for host: 192.168.0.114
[01:06:28.556] Setting up SSH remote "192.168.0.114"
[01:06:28.574] Acquiring local install lock: /var/folders/fd/3jw9659j2tqcc7cn_9czj7240000gp/T/vscode-remote-ssh-192.168.0.114-install.lock
[01:06:28.590] Looking for existing server data file at /Users/sku/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.0.114-622cb03f7e070a9670c94bae1a45d78d7181fbd4-0.64.0/data.json
[01:06:28.597] Found local server running: {"remoteListeningOn":{"port":45695},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1001","platform":"linux","connectionToken":"a11aa111-a111-1a11-a111-111aaa1a1a11","pid":7112,"ipcHandlePath":"/var/folders/fd/3jw9659j2tqcc7cn_9czj7240000gp/T/vscode-ssh-askpass-ccfa5a2dc70689bd4d4953a49219173a0ca23008.sock","socksPort":49708,"startupTime":1614755188281}
[01:06:28.669] Found running server - short-circuiting install
[01:06:28.677] Starting forwarding server. localPort 51076 -> socksPort 49708 -> remotePort 45695
[01:06:28.678] Forwarding server listening on 51076
[01:06:28.678] Waiting for ssh tunnel to be ready
[01:06:28.679] [Forwarding server 51076] Got connection 0
[01:06:28.681] Tunneled 45695 to local port 51076
[01:06:28.681] Resolved "ssh-remote+192.168.0.114" to "127.0.0.1:51076"
[01:06:28.803] ------

[01:06:28.939] [Forwarding server 51076] Got connection 1
[01:06:28.983] [Forwarding server 51076] Got connection 2
[01:06:30.658] Unhandled rejection: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[01:06:30.834] Unhandled rejection: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[03:37:00.156] ------

[03:37:00.157] SSH Resolver called for "ssh-remote+192.168.0.114", attempt 2, (Reconnection)
[03:37:00.159] SSH Resolver called for host: 192.168.0.114
[03:37:00.160] Setting up SSH remote "192.168.0.114"
[03:37:00.170] Acquiring local install lock: /var/folders/fd/3jw9659j2tqcc7cn_9czj7240000gp/T/vscode-remote-ssh-192.168.0.114-install.lock
[03:37:00.174] [Forwarding server 51076] Got connection 3
[03:37:00.178] Looking for existing server data file at /Users/sku/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.0.114-622cb03f7e070a9670c94bae1a45d78d7181fbd4-0.64.0/data.json
[03:37:00.187] Found local server running: {"remoteListeningOn":{"port":45695},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1001","platform":"linux","connectionToken":"a11aa111-a111-1a11-a111-111aaa1a1a11","pid":7112,"ipcHandlePath":"/var/folders/fd/3jw9659j2tqcc7cn_9czj7240000gp/T/vscode-ssh-askpass-ccfa5a2dc70689bd4d4953a49219173a0ca23008.sock","socksPort":49708,"startupTime":1614755188281}
[03:37:00.187] Running server is stale. Ignoring
[03:37:00.189] Using commit id "622cb03f7e070a9670c94bae1a45d78d7181fbd4" and quality "stable" for server
[03:37:00.197] Install and start server if needed
[03:37:00.211] Checking ssh with "ssh -V"
[03:37:00.281] > OpenSSH_8.1p1, LibreSSL 2.7.3

[03:37:00.285] Using SSH config file "/Users/sku/.ssh/config"
[03:37:00.287] askpass server listening on /var/folders/fd/3jw9659j2tqcc7cn_9czj7240000gp/T/vscode-ssh-askpass-9f6a9a3f1f75fd79cbdbf79ff01f02051bac635b.sock
[03:37:00.287] Spawning local server with {"ipcHandlePath":"/var/folders/fd/3jw9659j2tqcc7cn_9czj7240000gp/T/vscode-ssh-askpass-c0330a66925db72484af745c15c4a814edf52ce1.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52396","-o","ConnectTimeout=15","-F","/Users/sku/.ssh/config","192.168.0.114"],"dataFilePath":"/Users/sku/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.0.114-622cb03f7e070a9670c94bae1a45d78d7181fbd4-0.64.0/data.json"}
[03:37:00.288] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/fd/3jw9659j2tqcc7cn_9czj7240000gp/T/vscode-ssh-askpass-9f6a9a3f1f75fd79cbdbf79ff01f02051bac635b.sock"}
[03:37:00.292] Spawned 21555
[03:37:00.625] > local-server> Spawned ssh: 21556
[03:37:00.628] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[03:37:00.682] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:GiOO6oZuDtwxlMTpJHqx2Php4DjYQXea45ocbS2S6YM
[03:37:00.870] Got askpass request: {"request":"abcd123@192.168.0.114's password:"}
[03:37:00.875] Showing password prompt
[03:37:00.878] Listening for interwindow password on /var/folders/fd/3jw9659j2tqcc7cn_9czj7240000gp/T/vscode-ssh-askpass-7fc170c62b8644351dea63f1d0cc1885de1b291e.sock
[03:37:00.879] Writing password prompt to globalState
[04:07:15.173] Askpass request timed out
[04:07:15.204] Cleaning up other-window auth server
[04:07:15.771] Handling auth request failed: Error: Canceled
	at /Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:85753
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at T.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:5880)
	at P.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:6421)
	at /Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405069
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at T.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:5880)
	at P.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:6421)
	at ServerResponse.<anonymous> (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:306025)
	at ServerResponse.emit (events.js:315:20)
	at Socket.socketOnTimeout (_http_server.js:511:33)
	at Socket.emit (events.js:315:20)
	at Socket._onTimeout (net.js:482:8)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
[04:07:15.778] Unhandled rejection: Error: Handling auth request failed: Error: Canceled
	at /Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:85753
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at T.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:5880)
	at P.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:6421)
	at /Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405069
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at T.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:5880)
	at P.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:6421)
	at ServerResponse.<anonymous> (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:306025)
	at ServerResponse.emit (events.js:315:20)
	at Socket.socketOnTimeout (_http_server.js:511:33)
	at Socket.emit (events.js:315:20)
	at Socket._onTimeout (net.js:482:8)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
	at IncomingMessage.<anonymous> (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:306300)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at runNextTicks (internal/process/task_queues.js:66:3)
	at processTimers (internal/timers.js:489:9)
[04:07:15.807] stderr> Failed to get SSH credentials: Error in request: socket hang up
[04:07:15.808] stderr> ["/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/askpass-main.js","abcd123@192.168.0.114's","password:"]
[04:07:16.773] stderr> Connection reset by 192.168.0.114 port 22
[04:07:16.777] > local-server> ssh child died, shutting down
[04:07:16.788] Local server exit: 0
[04:07:16.788] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:GiOO6oZuDtwxlMTpJHqx2Php4DjYQXea45ocbS2S6YM
Failed to get SSH credentials: Error in request: socket hang up
["/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/askpass-main.js","abcd123@192.168.0.114's","password:"]
Connection reset by 192.168.0.114 port 22

[04:07:16.789] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, LibreSSL 2.7.3debug1: Server host key: ecdsa-sha2-nistp256 SHA256:GiOO6oZuDtwxlMTpJHqx2Php4DjYQXea45ocbS2S6YMFailed to get SSH credentials: Error in request: socket hang up["/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/askpass-main.js","abcd123@192.168.0.114's","password:"]Connection reset by 192.168.0.114 port 22
[04:07:16.790] Failed to parse remote port from server output
[04:07:16.794] Resolver error: Error: 
	at Function.Create (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:64126)
	at Object.t.handleInstallOutput (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:62865)
	at Object.t.tryInstallWithLocalServer (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405581)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:310867
	at async Object.t.withShowDetailsEvent (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:406337)
	at async /Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:404105
	at async S (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:400873)
	at async Object.t.resolveWithLocalServer (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:403732)
	at async Object.t.resolve (/Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:314879)
	at async /Users/sku/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:127:110431
[04:07:16.828] ------

`
Is there any way to  to use "Connect with current window to remote host" ?

**Comment by RaspiRepo** [comment]
Looks like placed this issue in wrong group, how do we move this to vscode UI group ?

**Comment by nturinski** [comment]
I believe you would want to place the issue here: https://github.com/microsoft/vscode-remote-release

You're trying to add an enhancement to the current Remote - SSH experience, correct?

**Comment by nturinski** [comment]
Closing due to this issue being in the wrong repository.  Please file this issue in the repo linked above.  Have a great day :)
